### ISSUE TITLE
Booting vpsadminos not working - Waiting for network to come online

### ISSUE THREAD

**Issue by dascgit** [vpsfreecz/vpsadminos#67]
I am trying to boot the vpsadminos ISO from https://iso.vpsadminos.org/ in a Virtual environment but I stuck at the boot process with the Message "Waiting for network to come online". I tried different network adapter types but still the same issue. Am I missing something?

Printscreen:
![image](https://github.com/vpsfreecz/vpsadminos/assets/125344779/0945d786-600c-49b0-aa93-f103237a770e)

**Comment by aither64** [comment]
What kind of network adapters have you tried? @graywolf already reported that the DHCP client had to be run manually, you could try:

```
$ /nix/store/*dhcpcd*/bin/dhcpcd
```

I'm not sure why it doesn't work on its own. You can then check `ip addr list` to see if ti worked.

The latest ISO build uses ping to check for connectivity, that might be an issue if you're using `user` network adapter. I've since improved it in 49b35e2, but I would have to rebuild the ISO.

If the network will be online when DHCP client is run, you can fool the `network-online` service by running:

```
$ sv stop network-online
$ mkdir -p /run/runit/service/network-online
$ touch /run/runit/service/network-online/done
```

**Comment by dascgit** [comment]
It worked with
`$ /nix/store/*dhcpcd*/bin/dhcpcd`

**Comment by aither64** [comment]
Ok, good to know. It's still an issue that it doesn't work out-of-the-box, let's keep it open so that I don't forget to look into it.
